version: '3.8'

services:
  flask-app:
    image: rosawang77/flask-mongo-app
    ports:
      - "5001:5001"
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

